# Generated by Django 3.2.9 on 2021-11-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('taken', models.DateTimeField(blank=True, null=True)),
                ('exp_return', models.DateTimeField(blank=True, null=True)),
                ('r_status', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
    ]
